/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Commands.h.zapt

#pragma once

#include <app/data-model/DecodableList.h>
#include <app/data-model/Encode.h>
#include <app/data-model/List.h>
#include <app/data-model/NullObject.h>
#include <app/data-model/Nullable.h>
#include <lib/core/DataModelTypes.h>
#include <lib/core/Optional.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/LowpanBleSensor/ClusterId.h>
#include <clusters/LowpanBleSensor/CommandIds.h>
#include <clusters/LowpanBleSensor/Enums.h>
#include <clusters/LowpanBleSensor/Structs.h>

#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace LowpanBleSensor {
namespace Commands {
// Forward-declarations so we can reference these later.

namespace AddSensorEp {
struct Type;
struct DecodableType;
} // namespace AddSensorEp

namespace RemoveSensorEp {
struct Type;
struct DecodableType;
} // namespace RemoveSensorEp

} // namespace Commands

namespace Commands {
namespace AddSensorEp {
enum class Fields : uint8_t
{
    kMacAddress = 0,
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::AddSensorEp::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::LowpanBleSensor::Id; }

    chip::CharSpan macAddress;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::AddSensorEp::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::LowpanBleSensor::Id; }
    static constexpr bool kIsFabricScoped = false;

    chip::CharSpan macAddress;

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace AddSensorEp
namespace RemoveSensorEp {
enum class Fields : uint8_t
{
    kEndpoint = 0,
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::RemoveSensorEp::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::LowpanBleSensor::Id; }

    uint64_t endpoint = static_cast<uint64_t>(0);

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::RemoveSensorEp::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::LowpanBleSensor::Id; }
    static constexpr bool kIsFabricScoped = false;

    uint64_t endpoint = static_cast<uint64_t>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace RemoveSensorEp
} // namespace Commands
} // namespace LowpanBleSensor
} // namespace Clusters
} // namespace app
} // namespace chip
